from .First import FirstScene
from .Network import NetworkScene
from .Guiboude import Guiboude
from .Cave import CaveScene
from .AStar import AStarScene
from .Locker1 import Locker1
from .Locker2 import Locker2
from .Locker3 import Locker3
import Scenes.Sub as Sub
